---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Chart.Name }}
          name: {{ .Chart.Name }}
        spec:
          serviceAccountName: {{ .Chart.Name }}
          priorityClassName: system-cluster-critical
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            args:
              - sync
              - --insecure-policy={{.Values.ecrMirrorSync.insecurePolicy}}
              - --debug={{.Values.ecrMirrorSync.debug}}
              - --render-table={{.Values.ecrMirrorSync.renderTable}}
              - --src-creds={{.Values.ecrMirrorSync.sourceCreds}}
          restartPolicy: "Never"